name = "JuliaBoyz"
uuid = "71841f54-e95a-47c3-8b4a-80af24220a07"
authors = ["elijahf22 <elijahf@mit.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
